### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by alienscience** [mariusmni/radixSA64#1]
Hello,
I tried to compile the software using `make` and I got the following error:

```
Invoking: GCC C++ Linker
g++ -L"/home/man09004/git/suffix-array/bpr-2.0/Release" -o "radixSA" ./src/runtimes.o   -lbpr-2.0
/usr/bin/ld: cannot find -lbpr-2.0
```
This seems to be causes by a dependency to the _bpr-2.0_ library. Do you know where I can get the dependency from? I have tried googling but I have had no luck in finding the library.

**Comment by mariusmni** [comment]
Hello, try removing line 6 in .project (BPR is a different algorithm, not needed unless you want to run a comparison with radixSA).
